var user = {
"login": "spencerwyckoff",
"id": 10204335,
"avatar_url": "https://avatars.githubusercontent.com/u/10204335?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/spencerwyckoff",
"html_url": "https://github.com/spencerwyckoff",
"followers_url": "https://api.github.com/users/spencerwyckoff/followers",
"following_url": "https://api.github.com/users/spencerwyckoff/following{/other_user}",
"gists_url": "https://api.github.com/users/spencerwyckoff/gists{/gist_id}",
"starred_url": "https://api.github.com/users/spencerwyckoff/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/spencerwyckoff/subscriptions",
"organizations_url": "https://api.github.com/users/spencerwyckoff/orgs",
"repos_url": "https://api.github.com/users/spencerwyckoff/repos",
"events_url": "https://api.github.com/users/spencerwyckoff/events{/privacy}",
"received_events_url": "https://api.github.com/users/spencerwyckoff/received_events",
"type": "User",
"site_admin": false,
"name": "Spencer Wyckoff",
"company": "",
"blog": "",
"location": "Atlanta, GA",
"email": "",
"hireable": false,
"bio": null,
"public_repos": 12,
"public_gists": 0,
"followers": 2,
"following": 1,
"created_at": "2014-12-16T05:39:32Z",
"updated_at": "2015-01-27T18:06:50Z"
}